name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.4, 2.7]
    env:
      PLATFORM: x86_64-linux
      TAGLIB_VERSION: 1.11.1
      SKIP_SWIG: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install SWIG v3.0.7
        run: |
          echo "Cloning SWIG v3.0.7..."
          git clone --depth 1 --branch v3.0.7 https://github.com/swig/swig.git
          echo "Configuring..."
          cd swig
          ./autogen.sh
          ./configure
          echo "Building..."
          make
          echo "Installing..."
          make install
      - name: Bundle install
        run: |
          gem install bundler
          bundle install
      - name: Generating SWIG wrappers
        run: |
          rake swig
      - name: Install taglib
        run: bundle exec rake vendor
      - name: Compile
        run: TAGLIB_DIR=$PWD/tmp/x86_64-linux/taglib-$TAGLIB_VERSION LD_LIBRARY_PATH=$PWD/tmp/x86_64-linux/taglib-$TAGLIB_VERSION/lib bundle exec rake compile
      - name: Test
        run: bundle exec rake test
