name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        ruby: [2.4, 2.7]
    
    env:
      PLATFORM: x86_64-linux
      TAGLIB_VERSION: 1.11.1
      SWIG_DIR: .swig-v3.0.7

    steps:
      - uses: actions/checkout@v2

      - name: Cache Bundle Install
        id: cache-bundle-install
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Bundle Install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Install taglib
        run: bundle exec rake vendor

#       - name: Cache SWIG v3.0.7
#         id: cache-swig-v307
#         uses: actions/cache@v2
#         with:
#           path: ~/$SWIG_DIR
#           key: ${{ runner.os }}-swig-v307-cache-5

      - name: Install SWIG v3.0.7
#         if: steps.cache-swig-v307.outputs.cache-hit != 'true'
        run: |
          sudo apt install yodl
          git clone --depth 1 --branch v3.0.7 https://github.com/swig/swig.git
          cd swig
          ./autogen.sh
          ./configure --prefix=$HOME/$SWIG_DIR --with-ruby=$(which ruby) --without-alllang
          make && make install
          cd ..

      - name: Generate SWIG wrappers
        run: |
          touch ext/*/*.i
          export PATH=$HOME/$SWIG_DIR/bin:$PATH && echo "PATH: " $PATH
          export SWIG_LIB=$HOME/$SWIG_DIR/share/swig/3.0.7 && echo "SWIG_LIB: " $SWIG_LIB
          swig -version && swig -swiglib
          TAGLIB_DIR=$PWD/tmp/x86_64-linux/taglib-$TAGLIB_VERSION LD_LIBRARY_PATH=$PWD/tmp/x86_64-linux/taglib-$TAGLIB_VERSION/lib bundle exec rake swig

      - name: Compile
        run: TAGLIB_DIR=$PWD/tmp/x86_64-linux/taglib-$TAGLIB_VERSION LD_LIBRARY_PATH=$PWD/tmp/x86_64-linux/taglib-$TAGLIB_VERSION/lib bundle exec rake compile

      - name: Run Tests
        run: bundle exec rake test
