name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.4, 2.7]
    env:
      PLATFORM: x86_64-linux
      TAGLIB_VERSION: 1.11.1
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Bundle install
        run: |
          gem install bundler
          bundle install
      - name: Install taglib
        run: bundle exec rake vendor
      - name: Cache SWIG v3.0.7
        id: cache-swig
        uses: actions/cache@v2
        with:
          path: swig
          key: ${{ runner.os }}-swig
      - name: Install SWIG v3.0.7
        if: steps.cache-swig.outputs.cache-hit != 'true'
        run: |
          sudo apt install yodl
          git clone --depth 1 --branch v3.0.7 https://github.com/swig/swig.git
          cd swig
          ./autogen.sh
          ./configure
          make
          sudo make install
      - name: Generate SWIG wrappers
        run: |
          touch touch ext/*/*.i
          TAGLIB_DIR=$PWD/tmp/x86_64-linux/taglib-$TAGLIB_VERSION LD_LIBRARY_PATH=$PWD/tmp/x86_64-linux/taglib-$TAGLIB_VERSION/lib bundle exec rake swig
      - name: Compile
        run: TAGLIB_DIR=$PWD/tmp/x86_64-linux/taglib-$TAGLIB_VERSION LD_LIBRARY_PATH=$PWD/tmp/x86_64-linux/taglib-$TAGLIB_VERSION/lib bundle exec rake compile
      - name: Test
        run: bundle exec rake test
