name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        ruby: [2.4, 2.7]
    
    env:
      PLATFORM: x86_64-linux
      TAGLIB_VERSION: 1.11.1
      SWIG_DIR: .swig-v3.0.7

    steps:
      - uses: actions/checkout@v2      
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      
      - name: Bundle install
        run: |
          gem install bundler
          bundle install

      - name: Install taglib
        run: bundle exec rake vendor

      - name: Cache SWIG v3.0.7
        id: cache-swig-v307
        uses: actions/cache@v2
        with:
          path: $PWD/swig/$SWIG_DIR
          key: ${{ runner.os }}-swig-v307-cache-1

      - name: Install SWIG v3.0.7
        if: steps.cache-swig-v307.outputs.cache-hit != 'true'
        run: |
          sudo apt install yodl
          git clone --depth 1 --branch v3.0.7 https://github.com/swig/swig.git
          cd swig
          ./autogen.sh
          ./configure --prefix=$PWD/$SWIG_DIR --with-ruby=$(which ruby) --without-alllang
          make && make install

      - name: Generate SWIG wrappers
        run: |
          touch ext/*/*.i
          export PATH=$PWD/swig/$SWIG_DIR/bin/:$PATH
          echo "PATH: " $PATH
          export SWIG_LIB=$PWD/swig/$SWIG_DIR/share/swig/3.0.7/
          echo "SWIG_LIB: " $SWIG_LIB
          swig -version && swig -swiglib
          TAGLIB_DIR=$PWD/tmp/x86_64-linux/taglib-$TAGLIB_VERSION LD_LIBRARY_PATH=$PWD/tmp/x86_64-linux/taglib-$TAGLIB_VERSION/lib bundle exec rake swig

      - name: Compile
        run: TAGLIB_DIR=$PWD/tmp/x86_64-linux/taglib-$TAGLIB_VERSION LD_LIBRARY_PATH=$PWD/tmp/x86_64-linux/taglib-$TAGLIB_VERSION/lib bundle exec rake compile

      - name: Test
        run: bundle exec rake test
