name: ci

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04]
        ruby: [2.5, 2.6, 2.7]

    runs-on: ${{ matrix.os }}

    env:
      MAKEFLAGS: -j2
      PLATFORM: x86_64-linux
      TAGLIB_VERSION: 1.11.1
      SWIG_DIR: .swig-v3.0.7

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Cache SWIG v3.0.7
        id: cache-swig
        uses: actions/cache@v2
        with:
          path: ~/${{ env.SWIG_DIR }}
          key: swig-${{ matrix.os }}-v3.0.7-2

      - name: Install SWIG v3.0.7
        if: steps.cache-swig.outputs.cache-hit != 'true'
        run: |
          sudo apt install yodl
          git clone --depth 1 --branch v3.0.7 https://github.com/swig/swig.git
          cd swig
          ./autogen.sh
          ./configure --prefix=$HOME/$SWIG_DIR --with-ruby=$(which ruby) --without-alllang
          make
          make install

#      - name: Test swig
#        run: |
#          ls -R $HOME/$SWIG_DIR
#          export PATH=$HOME/$SWIG_DIR/bin:$PATH
#          echo "PATH: " $PATH
#          swig -version && swig -swiglib

#      - name: Cache Bundle Install
#        id: cache-bundle-install
#        uses: actions/cache@v2
#        with:
#          path: vendor/bundle
#          key: bundle-${{ matrix.os }}-ruby${{ matrix.ruby }}

      - name: Bundle Install
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Cache taglib
        id: cache-taglib
        uses: actions/cache@v2
        with:
          path: tmp/${{ env.PLATFORM }}/taglib-${{ env.TAGLIB_VERSION }}
          key: taglib-${{ matrix.os }}-v${{ env.TAGLIB_VERSION }}-1

      - name: Install taglib
        if: steps.cache-taglib.outputs.cache-hit != 'true'
        run: bundle exec rake vendor

      - name: Generate SWIG wrappers
        run: |
          touch ext/*/*.i
          export PATH=$HOME/$SWIG_DIR/bin:$PATH
          TAGLIB_DIR=$PWD/tmp/$PLATFORM/taglib-$TAGLIB_VERSION bundle exec rake swig

      - name: Compile
        run: TAGLIB_DIR=$PWD/tmp/$PLATFORM/taglib-$TAGLIB_VERSION bundle exec rake compile

      - name: Run Tests
        run: LD_LIBRARY_PATH=$PWD/tmp/$PLATFORM/taglib-$TAGLIB_VERSION/lib bundle exec rake test
